/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UploadIndexRouteImport } from './routes/upload/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as RecordingsIndexRouteImport } from './routes/recordings/index'
import { Route as RecordIndexRouteImport } from './routes/record/index'
import { Route as RecordingsIdIndexRouteImport } from './routes/recordings/$id/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UploadIndexRoute = UploadIndexRouteImport.update({
  id: '/upload/',
  path: '/upload/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const RecordingsIndexRoute = RecordingsIndexRouteImport.update({
  id: '/recordings/',
  path: '/recordings/',
  getParentRoute: () => rootRouteImport,
} as any)
const RecordIndexRoute = RecordIndexRouteImport.update({
  id: '/record/',
  path: '/record/',
  getParentRoute: () => rootRouteImport,
} as any)
const RecordingsIdIndexRoute = RecordingsIdIndexRouteImport.update({
  id: '/recordings/$id/',
  path: '/recordings/$id/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/record/': typeof RecordIndexRoute
  '/recordings/': typeof RecordingsIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/upload/': typeof UploadIndexRoute
  '/recordings/$id/': typeof RecordingsIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/record': typeof RecordIndexRoute
  '/recordings': typeof RecordingsIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/upload': typeof UploadIndexRoute
  '/recordings/$id': typeof RecordingsIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/record/': typeof RecordIndexRoute
  '/recordings/': typeof RecordingsIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/upload/': typeof UploadIndexRoute
  '/recordings/$id/': typeof RecordingsIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/record/'
    | '/recordings/'
    | '/settings/'
    | '/upload/'
    | '/recordings/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/record'
    | '/recordings'
    | '/settings'
    | '/upload'
    | '/recordings/$id'
  id:
    | '__root__'
    | '/'
    | '/record/'
    | '/recordings/'
    | '/settings/'
    | '/upload/'
    | '/recordings/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RecordIndexRoute: typeof RecordIndexRoute
  RecordingsIndexRoute: typeof RecordingsIndexRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
  UploadIndexRoute: typeof UploadIndexRoute
  RecordingsIdIndexRoute: typeof RecordingsIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upload/': {
      id: '/upload/'
      path: '/upload'
      fullPath: '/upload/'
      preLoaderRoute: typeof UploadIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recordings/': {
      id: '/recordings/'
      path: '/recordings'
      fullPath: '/recordings/'
      preLoaderRoute: typeof RecordingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/record/': {
      id: '/record/'
      path: '/record'
      fullPath: '/record/'
      preLoaderRoute: typeof RecordIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recordings/$id/': {
      id: '/recordings/$id/'
      path: '/recordings/$id'
      fullPath: '/recordings/$id/'
      preLoaderRoute: typeof RecordingsIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RecordIndexRoute: RecordIndexRoute,
  RecordingsIndexRoute: RecordingsIndexRoute,
  SettingsIndexRoute: SettingsIndexRoute,
  UploadIndexRoute: UploadIndexRoute,
  RecordingsIdIndexRoute: RecordingsIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
