/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UploadIndexRouteImport } from './routes/upload/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as RecordIndexRouteImport } from './routes/record/index'
import { Route as FilesIndexRouteImport } from './routes/files/index'
import { Route as FilesIdIndexRouteImport } from './routes/files/$id/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UploadIndexRoute = UploadIndexRouteImport.update({
  id: '/upload/',
  path: '/upload/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const RecordIndexRoute = RecordIndexRouteImport.update({
  id: '/record/',
  path: '/record/',
  getParentRoute: () => rootRouteImport,
} as any)
const FilesIndexRoute = FilesIndexRouteImport.update({
  id: '/files/',
  path: '/files/',
  getParentRoute: () => rootRouteImport,
} as any)
const FilesIdIndexRoute = FilesIdIndexRouteImport.update({
  id: '/files/$id/',
  path: '/files/$id/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/files/': typeof FilesIndexRoute
  '/record/': typeof RecordIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/upload/': typeof UploadIndexRoute
  '/files/$id/': typeof FilesIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/files': typeof FilesIndexRoute
  '/record': typeof RecordIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/upload': typeof UploadIndexRoute
  '/files/$id': typeof FilesIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/files/': typeof FilesIndexRoute
  '/record/': typeof RecordIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/upload/': typeof UploadIndexRoute
  '/files/$id/': typeof FilesIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/files/' | '/record/' | '/settings/' | '/upload/' | '/files/$id/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/files' | '/record' | '/settings' | '/upload' | '/files/$id'
  id:
    | '__root__'
    | '/'
    | '/files/'
    | '/record/'
    | '/settings/'
    | '/upload/'
    | '/files/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FilesIndexRoute: typeof FilesIndexRoute
  RecordIndexRoute: typeof RecordIndexRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
  UploadIndexRoute: typeof UploadIndexRoute
  FilesIdIndexRoute: typeof FilesIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upload/': {
      id: '/upload/'
      path: '/upload'
      fullPath: '/upload/'
      preLoaderRoute: typeof UploadIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/record/': {
      id: '/record/'
      path: '/record'
      fullPath: '/record/'
      preLoaderRoute: typeof RecordIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/files/': {
      id: '/files/'
      path: '/files'
      fullPath: '/files/'
      preLoaderRoute: typeof FilesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/files/$id/': {
      id: '/files/$id/'
      path: '/files/$id'
      fullPath: '/files/$id/'
      preLoaderRoute: typeof FilesIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FilesIndexRoute: FilesIndexRoute,
  RecordIndexRoute: RecordIndexRoute,
  SettingsIndexRoute: SettingsIndexRoute,
  UploadIndexRoute: UploadIndexRoute,
  FilesIdIndexRoute: FilesIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
